# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:22:27+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    RdcerCertificatePostRequest,
    RdcerCertificatePostResponse,
    RdcerCertificatePostResponse1,
    RdcerCertificatePostResponse2,
    RdcerCertificatePostResponse3,
    RdcerCertificatePostResponse4,
    RdcerCertificatePostResponse5,
    RdcerCertificatePostResponse6,
    Ror1bCertificatePostRequest,
    Ror1bCertificatePostResponse,
    Ror1bCertificatePostResponse1,
    Ror1bCertificatePostResponse2,
    Ror1bCertificatePostResponse3,
    Ror1bCertificatePostResponse4,
    Ror1bCertificatePostResponse5,
    Ror1bCertificatePostResponse6,
)

app = MCPProxy(
    description='Revenue Department of Odisha(http://revenueodisha.gov.in/) provides Copy of Registered Deed(Sale, Gift) of year 2010 onward and Copy of Record of Rights (RoR).',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Revenue Department, Odisha',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/revenueodisha/v3'}],
)


@app.post(
    '/rdcer/certificate',
    description=""" API to verify Copy of Registered Deed. """,
    tags=['property_documentation'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def rdcer(body: RdcerCertificatePostRequest = None):
    """
    Copy of Registered Deed
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/ror1b/certificate',
    description=""" API to verify Records of Rights. """,
    tags=['property_documentation'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def ror1b(body: Ror1bCertificatePostRequest = None):
    """
    Records of Rights
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
